### PR TITLE
Testing: use I/O to report success, not #clear*

### PR DESCRIPTION
**Pull request by hjorthjort**
I found the use of `#clearConfig` and similar a bit of a crude tool, and it requires keeping both the `#clear` operations and the success file up to date with all changes to the configuration and its default values.

Do you think this solution is acceptable? It could of course be made cleaner, by writing to a status file directly instead of using `stdout`, but I think this is still an improvement.

### CODE REVIEW

**Comment by ehildenb** [comment]
Why not use the exit-code method that KEVM uses instead @hjorthjort ? That way we still can have the output configuration for inspection.

Just annotate a cell like this `<exit-code exit=""> 1 </exit>`, and then have a rule which changes the value of the cell to `0` on test success.

**Comment by hjorthjort** [comment]
> Why not use the exit-code method that KEVM uses instead @hjorthjort ? That way we still can have the output configuration for inspection.
> 
> Just annotate a cell like this `<exit-code exit=""> 1 </exit>`, and then have a rule which changes the value of the cell to `0` on test success.

Thanks! Had a feeling I was reinventing the wheel. This is better.

**Review by ehildenb — APPROVED** [review]

**Comment by ehildenb** [comment]
@hjorthjort before you merge this, please check:

-  That it exits with code 1 correctly on an intentionally failing test.
-  That you don't want a way to reset the exit code to 1 at the beginning of a new test or something. Current approach where you wait for K cell to go empty seems good, but maybe you want to have multiple tests in a file. Up to you.

**Comment by hjorthjort** [comment]
> @hjorthjort before you merge this, please check:
> 
>     * That it exits with code 1 correctly on an intentionally failing test.
> 
Confirmed

>     * That you don't want a way to reset the exit code to 1 at the beginning of a new test or something. Current approach where you wait for K cell to go empty seems good, but maybe you want to have multiple tests in a file. Up to you.

Will do as it comes up. Good point.

**Pull request merged**
